name: CI for ConteneurCreator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install colorama pytest
    
    - name: Run tests
      run: pytest -v
    
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: pytest-report.xml
      if: always()

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: pytest-report.xml